# Generated by Django 4.2.5 on 2024-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('shampoo', 'Shampoo'), ('acondicionador', 'Acondicionador'), ('Crema Capilar', 'Crema Capilar'), ('Tintura', 'Tintura')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
