# Generated by Django 4.2.5 on 2024-11-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_cart_alter_producto_categoria_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
