# Generated by Django 5.0.9 on 2024-11-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=15, verbose_name='Categoria')),
                ('Stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('Imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
