# Generated by Django 5.0.9 on 2024-11-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Stock',
            new_name='stock',
        ),
    ]
