# Generated by Django 5.0.9 on 2024-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0002_rename_imagen_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('shampoo', 'Shampoo'), ('acondicionador', 'Acondicionador'), ('Crema Capilar', 'Crema Capilar'), ('Tintura', 'Tintura')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
