# Generated by Django 5.0.9 on 2024-11-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0003_alter_producto_categoria_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Shampoo', 'SHAMPOO'), ('Acondicionador', 'ACONDICIONADOR'), ('Crema capilar', 'CREMA CAPILAR'), ('Tintura', 'TINTURA')], max_length=20),
        ),
    ]
